# .github/deploy_config.yml
# This file defines the default deployment status for each screen.
# Set the value to 'true' for screens you want to deploy by default
# when the workflow is run without specific overriding inputs.

default_screen_deployment_status:
  "login-id": true