name: Code Quality CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  validate-manifest:
    name: Validate Manifest Structure
    runs-on: ubuntu-22.04-2cpu-8ram-75ssd
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          
      - name: Validate manifest
        uses: ./.github/actions/validate-manifest
        with:
          manifest-path: './manifest.json'
          strict-mode: 'true'

  react-js-quality:
    name: React-JS Quality Checks
    runs-on: ubuntu-22.04-2cpu-8ram-75ssd
    if: contains(github.event.head_commit.modified, 'react-js/') || contains(join(github.event.pull_request.changed_files.*.filename || '', ' '), 'react-js/') || github.event_name == 'pull_request'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: 'react-js/package-lock.json'
          
      - name: Install dependencies
        working-directory: react-js
        run: npm ci
        
      - name: Lint check
        working-directory: react-js
        run: npm run lint:check
        
      - name: Type check
        working-directory: react-js
        run: npx tsc --noEmit
        
      - name: Test
        working-directory: react-js
        run: npm test -- --coverage --watchAll=false --passWithNoTests
        
      - name: Build
        working-directory: react-js
        run: npm run build

  react-quality:
    name: React Quality Checks  
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.modified, 'react/') || contains(join(github.event.pull_request.changed_files.*.filename || '', ' '), 'react/') || github.event_name == 'pull_request'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: React sample status
        run: |
          echo "React sample is under development"
          echo "Skipping quality checks until implementation is ready"